import Head from "next/head";
import Image from "next/image";
import About from "../components/About";
import Header from "../Components/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>StartUP Women</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Mukta:wght@300;400;500;700;800;900&family=Playfair+Display:ital,wght@0,700;1,400&family=Raleway:wght@900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Header />
      <About />
    </div>
  );
}
