import Head from "next/head";
import Image from "next/image";
import About from "../components/About";
import Header from "../components/Header";
import Host from "../components/Host";
import Program from "../components/Program";
import Speakers from "../components/Speakers";
import Tickets from "../components/Tickets";
import Host1 from "../public/speakers/Host.png";
import Host2 from "../public/speakers/Host2.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>StartUP Women</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Mukta:wght@300;400;500;700;800;900&family=Playfair+Display:ital,wght@0,700;1,400&family=Raleway:wght@900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header />
      <About />
      <Speakers />
      <Host
        src={Host1}
        title="Start your dream project"
        quote="“Fortune smiles on the brave. You will never know what you are
              capable of until you risk it. ”"
        name="~ Cheryl Sandberg"
      />
      <Program />
      <div className="quote py-5">
        <em className="display-5 d-block text-center text-light">
          "Control your destiny, or someone else will do it."
        </em>

        <h4 className="h5 text-center text-light pt-3">Joanne Welch</h4>
      </div>
      <Tickets />
    </div>
  );
}
